### ISSUE TITLE
[Bug]: In the version 1.12.1 and greater. When reviewing flashCards. I can no longer click an image to zoom in and out 

### ISSUE THREAD

**Issue by SimoAbjaou** [st3v3nmw/obsidian-spaced-repetition#1101] opened 2024-09-28 12:02 UTC
### Describe the bug

When reviewing flashCards contaning an image. Using the plugin Image Toolkit, I can't : click an image to displayed it in a popup layer and zoom it in and out.

I have two obsidian vault, with the same plugin image Toolkit. One with obsidian-spaced-repetition 1.12.0 and the second vault with 1.12.8 . I can only click and zoom the image on the one with obsidian-spaced-repetition version 1.12.0. Once I use the version 1.12.1 I reproduce the issue.

How can I be able to click the image and zoom with the new version recent version ?

### Expected behavior

Using the plugin Image Toolkit, I click an image, I can view it. I can zoom in and out.

### OS of your device

Win11

### Obsidian version

v1.6.7

### Plugin version

1.12.1 and greater

**Comment by ronzulu** [comment] 2024-09-29 01:18
> I have two obsidian vault, with the same plugin image Toolkit. 

What is `plugin image Toolkit`?

> One with obsidian-spaced-repetition 1.12.0 and the second vault with 1.12.8 .

I see that you've updated the problem description to "1.12.1 and greater". To reduce possible confusion, please update this sentence as well.

### Files

To make this easier for any developer to reproduce the issue, please supply the files. Presumably this means at least one markdown file and one image file.

### Changes to rendering

I know of one change relevant to rendering, but this occurred in 1.12.5, not 1.12.1. We stopped using the deprecated Obsidian api `MarkdownRenderer.renderMarkdown`, and switched to using `MarkdownRenderer.render`. The obsidian documentation didn't mention the the differences between the 2, and this led to an issue that was resolved in https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/1062.

[FIX] Not scroll back to top after review (https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/971)

**Comment by SimoAbjaou** [comment] 2024-09-29 02:20
Hi @ronzulu , thank you for your response. 

> What is plugin image Toolkit?

It is the plugin image Toolkit that lets me use some viewing functions on the image like zoom in and out that are not implemented by default in obisidian. I use the last version 1.4.1. 

In the plugin image Toolkit documentation: https://github.com/sissilab/obsidian-image-toolkit : When you click an image, it will be popped up and you can preview, zoom, move, rotate, flip, invert and copy the image.


> I see that you've updated the problem description to "1.12.1 and greater". To reduce possible confusion, please update this sentence as well. 

I have mentioned the 1.12.0 version because it is the last version in which I can click to pop up the image in a new layer (yes, you have to install the image Toolkit plugin before), and zoom it in and out. If I use the 1.12.1 version I have this issue. So, I have identified that this issue is reproduced from the 1.12.1 version and greater. I think the commit in 1.12.1 that introduced the issue is  "[Overhaul] Implementation of a more consistent & modern UI" (https://github.com/st3v3nmw/obsidian-spaced-repetition/releases/tag/1.12.1). Maybe, this can help to identify the main reason.

### Files

the file : [test-image-zoom-when-reviewing-flashcards.md](https://github.com/user-attachments/files/17177314/test-image-zoom-when-reviewing-flashcards.md)
the image : ![Pasted image 20240928165435](https://github.com/user-attachments/assets/2b169204-f3a4-4819-95d3-5b198fcc3aac)
or you can use any image you would like.

> Changes to rendering

Maybe, in the 1.12.1 you have used some new rendering functions that are not updated yet in the image Toolkit plugin.

### Expected behavior

Install the 1.12.0 version of obsidian-spaced-repetition.
install the 1.4.1 version of obsidian-image-toolkit and enable it.
Review the flashcards with the given files.
The result should be like this : 
![image](https://github.com/user-attachments/assets/ab7e3cf1-4bd5-4c5c-93d8-7417ae277aec)

### Reproduce the issue

Install the 1.12.1 version of obsidian-spaced-repetition. Because it is the first version that I have noticed the issue. It is also in the 1.12.8 one.
Repeat the same other steps.

**Comment by ronzulu** [comment] 2024-09-29 22:48
Hi @SimoAbjaou 

I'm wondering if you will have better luck reporting the issue to the image toolkit plug-in developers.

My thinking is that for us it would be a trial and error experimental approach to finding out what changed between 1.12.0 and 1.12.1. And at that point we probably wouldn't know what to do to fix it.

On the other hand the image toolkit developers would presumably be able to quickly determine the reason why their plug-in isn't working with 1.12.1. And it may not be difficult for them to enhance their plug-in to be more tolerant of whatever was introduced in 1.12.1. Or at least provide technical info on what their plug-in is looking for to find images for it to work with.

Cheers
Ronny

**Comment by SimoAbjaou** [comment] 2024-09-30 00:31
Hello @ronzulu,

Ok I will open a ticket in their repository to see if they can help.

Thank you

**Closed** 2024-10-07 19:36 UTC
Labels: bug
