### ISSUE TITLE
[BUG]failed to open the next note automatically after reviewing another

### ISSUE THREAD

**Issue by ZuoAoyu** [st3v3nmw/obsidian-spaced-repetition#582] opened 2023-01-06 10:22 UTC
**Describe the bug**
failed to open the next note automatically after reviewing another

**Versions (please complete the following information):**

-   OS: win10
-   Obsidian version: 1.1.9
-   Plugin version: 1.9.3

**Additional context**
I enabled this option in settings, but it sometimes works, sometimes does not work, and most of the time does not work.

**Comment by karimodm** [comment] 2023-03-22 14:21
+1 for this issue! It actually forces to vote twice on the same note to actually get to the next one, thus altering the score because of such double vote.

**Comment by karimodm** [comment] 2024-01-02 14:35
Duplicate of #424

**Comment by st3v3nmw** [comment] 2024-01-22 16:57
This has been fixed in the latest release (v1.11.1). I'm closing this issue but if it's still occurring, please re-open the issue and we'll look into it further

**Closed by st3v3nmw** 2024-01-22 16:57 UTC
Labels: bug
