### ISSUE TITLE
Workflow for limiting new cards per day

### ISSUE THREAD

**Issue by PaperOrb** [st3v3nmw/obsidian-spaced-repetition#454] opened 2022-06-11 17:15 UTC
For anyone searching this feature on the repo: 

I just wanted to add a simple workflow (but maybe not immediately obvious) for limiting new cards per day until a proper feature is added. At the top of my note, I'll place a single ). Then I just move the <!-- down the page 10 cards worth let's say to unlock 10 new cards for that day. Rinse/repeat. Not pretty but it gets the job done.

**Comment by st3v3nmw** [comment] 2022-10-12 18:54
Duplicate of #505, will track the fix there

**Closed by st3v3nmw** 2022-10-12 18:54 UTC
