### ISSUE TITLE
[BUG] Cloze seems to misbehave when separator for inlined flashcards is "->"

### ISSUE THREAD

**Issue by andrewShinjo** [st3v3nmw/obsidian-spaced-repetition#836] opened 2024-01-12 06:44 UTC
**Describe the bug**

When I set the separator for inlined flashcard to "->", it started causing the cloze to misbehave. I changed the inlined flashcard back to the default "::" and it got fixed. I think the "->" symbol confused the flashcard plugin because the flashcard review metadata uses "->".

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/22268862/fabb0062-cd30-461d-bd56-51fc5ef7cbd8)

For example, in this screenshot:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/22268862/b2b1121f-98d6-453a-b0a6-d601cdd4d5b9)

I answered the question on line 5, and I only answered one of the four cloze questions. So, there should be three cloze questions left in the queue.

This is what the queue looks like when I open it:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/22268862/010ed224-5bac-4576-845d-d0864ebd2898)

When I open the flashcard, it is blank:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/22268862/973c85e9-3042-4352-96db-255a7c7013e4)

Then, when I exit the flashcard, the due date of the cloze disappeared:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/22268862/212fc534-571c-417c-b68d-60687538ae83)

**To Reproduce**

1. Change the separator for inlined flashcard to "->"
2. Create a document with the following text:

Q -> A

This is a cloze: {{apple}} {{banana}} {{mango}} {{orange}}

3. Open the flashcard review.
4. Answer the "Q -> A" question, and one of the cloze questions.
5. Close the flashcard review.
6. Re-open the flashcard review.
7. Should have incorrect flashcard count, and a blank flashcard when opened.

**Expected behavior**

Flashcards properly counted, and cloze flashcard not blank when opened.

**Screenshots**

No errors in the developer console.

**Versions (please complete the following information):**

'5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.5.3 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36'

**Additional context**
Add any other context about the problem here (e.g. the markdown producing the error).

**Comment by ronzulu** [comment] 2024-01-12 12:35
Hi @andrewShinjo thanks for reporting the issue.

I notice that in the description you have used the character string `->`, in the screenshot you have presumably a Unicode character:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/18433c1c-f3bd-488f-afcb-eddb669aaeb2)

Could you please attach your actual Markdown file so I can try to reproduce.

Cheers
Ronny

**Comment by andrewShinjo** [comment] 2024-01-12 18:58
Hi, I think my Obsidian just automatically renders "->" as the unicode arrow character. When I open the markdown file in a different text editor, the unicode arrow character just appears as "->"

I attached the markdown file. I believe this markdown file should be set up to generate the error I posted above.

[test-document.md](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/13922997/test-document.md)

Thank you for your time.

**Comment by ronzulu** [comment] 2024-01-13 00:31
Hi @andrewShinjo 

Thanks for sending the Markdown file. There seems to be 3 issues, which may or may not be totally related.

1. Rendering of the "->".

On my system it renders as text "->". 

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/79be0f9c-8b9b-4631-9b16-76dd0eba14eb)

I had a look at obsidian options, and couldn't find any relevant setting. Do you have any community plug-ins that might be doing this?

2. The card count shown after reviewing the "->" question and one of the cloze cards.

Functionality depends on the setting of the "bury siblings". With your cloze question, the single question generates 4 separate cards, which are termed "siblings".

What settings do you have for:

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/d6831c3d-dee7-4be6-a51f-b3479dc244fb)

3. Selecting the deck to review and seeing a blank card.

It's quite a weird problem! Given that the plug-in works when you have the standard "::" in-line separator, we have to conclude that it's something about the "->" and as I can't reproduce it, something on your system presumably is part of the mystery.

And if the "->" is just a rendering issue, then why is the plug-in affected? You've shown that the file itself uses standard characters for the "->", and I would have thought that the plug-in would therefore also be receiving from obsidian the text of the note using standard characters.

# Next Steps

If you can work out what on your system might be unusual, causing the conversion of "->" to "→", that would be great.

Out of curiosity what happens if you change the in-line separator to "-->" (with 2 dashes before the ">")?

Otherwise we might need to send through a version of the plug-in with custom logging to try to identify what's going wrong. But given the backlog of issues, there might not an immediate solution if the solution requires code changes.

Cheers
Ronny

**Comment by andrewShinjo** [comment] 2024-01-13 05:52
Hi, I believe my Obsidian automatically changes "->" to the unicode arrow symbol because my default font for my operating system is "Inter". When I changed the font to Arial, I got the usual arrow like this: "->". 

After changing the font to Arial, the error is still generated. The error also existed when the in-line separator is "-->", but it did not exist when the in-line separator is "--->".

Also, my "bury sibling cards until the next day?" setting is turned off.

I changed my in-line separator back to the default "::" so this issue isn't that big of a deal if it's unresolved. Might be some issue unique to my computer.

Thank you for your time.

**Comment by ronzulu** [comment] 2024-01-23 10:22
Hi @andrewShinjo because you have a suitable workaround, and the issue might be specific to your setup, I'll close this now.

If we didn't have a large backlog, I'd like to investigate. I'm curious what is causing this problem!

Cheers
Ronny

**Closed by ronzulu** 2024-01-23 10:22 UTC
Labels: bug
