### ISSUE TITLE
[FEAT]Consider a better interval repetition algorithm - FSRS4

### ISSUE THREAD

**Issue by dapaning** [st3v3nmw/obsidian-spaced-repetition#624] opened 2023-02-09 07:31 UTC
Here's a link to the author, the review algorithm has been applied to anki(PC), remnote, etc

https://github.com/open-spaced-repetition/fsrs4anki

**Comment by maggaou** [comment] 2023-02-09 08:24
Duplicate of #516

**Closed** 2023-02-09 16:15 UTC
Labels: enhancement
