### ISSUE TITLE
[FEAT] Please add an option to hide the note review queue

### ISSUE THREAD

**Issue by shaggyfeng** [st3v3nmw/obsidian-spaced-repetition#389] opened 2022-01-29 21:43 UTC
**Is your feature request related to a problem? Please describe.**
There is no way to hide the note review queue one the side bar. Every time I open Obsidian.md, the note review queue will show up again. The plugin also takes up too much space on the status bar. To save space, I have to disable the plugin when I do not need to review cards. It will be much easier for me to simply choose what to show or not in the setting.

**Describe the solution you'd like**
1. Please add an option in the setting to hide the note review queue.
2. Please add an option in the setting to hide the info on the status bar.

**Comment by AB1908** [comment] 2022-01-30 23:17
Can you post a screenshot showing this?

**Comment by shaggyfeng** [comment] 2022-01-31 09:25
> Can you post a screenshot showing this?

There is no bug. Things look normal. It is just a request for having options to not always respawn the Review notes sidebar and hide the all the stats on statusbar.

**Comment by AB1908** [comment] 2022-01-31 10:05
I never said there was a bug haha. Just wanted to make sure that I was thinking of the right thing. In any case, the status bar stuff can be hidden with a bit of css.

**Comment by shaggyfeng** [comment] 2022-02-02 01:09
> I never said there was a bug haha. Just wanted to make sure that I was thinking of the right thing. In any case, the status bar stuff can be hidden with a bit of css.

Any thoughts on how to disable the auto-respawn note review queue on the side bar? I may need to learn JS to figure that out.

**Comment by AB1908** [comment] 2022-02-02 09:43
I'll test it out at some point and let you know. I suspect it isn't possible without actually changing the plugin code.

**Comment by st3v3nmw** [comment] 2022-10-12 19:40
Duplicate of #458 
Will be tracking this issue there

**Closed by st3v3nmw** 2022-10-12 19:40 UTC
Labels: enhancement
