### ISSUE TITLE
[FEAT] Allow replaying flashcards without waiting

### ISSUE THREAD

**Issue by jabbalaci** [st3v3nmw/obsidian-spaced-repetition#432] opened 2022-04-01 06:42 UTC
Currently, I'm forced to select if the card was hard / normal / easy. However, very often, I'd like to replay all my cards in the deck. But, even if I choose hard, I should wait some days. What if I don't want to wait at all?

Current workaround: remove the `<!-- ... -->` lines from the source. But it's a pain.

Request: next to hard / normal / easy, there should be a "Next" button that doesn't register anything in the .md source code. This way the deck could be replayed immediately, without waiting.

**Comment by navakelvin** [comment] 2022-05-01 22:50
For the love of god, this needs to be implemented. One solution would be to allow changing the interval from hard to hours, minutes, or even seconds.

Waiting a whole day is so painful and unproductive.

**Comment by st3v3nmw** [comment] 2022-10-12 19:25
Duplicate of #503 
That issue is already triaged, will track this feature request there

**Closed by st3v3nmw** 2022-10-12 19:25 UTC
Labels: enhancement
