### ISSUE TITLE
[Bug]: Card being made when there is cloze but no separator, a card with cloze should only be made when there are both separator and highlight

### ISSUE THREAD

**Issue by Barmaid1076** [st3v3nmw/obsidian-spaced-repetition#1030] opened 2024-07-29 09:51 UTC
### Describe the bug

[Bug]: Card being made when there is cloze but no separator, a card with cloze should only be made when there are both separator and highlight

### To Reproduce

a card being made when it contains
#flashcards 
==cloze== card

however it should be a card only if there is a seperator or preferably a self-defined character, as highlights or double brackets are widely used 

#flashcards 
==cloze== card :: answer

### Expected behavior

a card was not made

### OS of your device

win10

### Obsidian version

latest

### Plugin version

latest

### Installer version

latest

**Comment by Barmaid1076** [comment] 2024-07-29 09:53
also brackets are incompatible with latex

**Comment by ronzulu** [comment] 2024-07-29 13:34
Hi @Barmaid1076 This seems to be a duplicate of #581. 

Is there anything you are after that isn't covered by #581?

**Comment by Barmaid1076** [comment] 2024-07-29 21:05
Sorry, didn't find that issue when I posted, most are covered by that issue, thanks for replying

**Comment by ronzulu** [comment] 2024-07-30 13:17
No problem, I'll close this and keep #581 open.

**Closed by ronzulu** 2024-07-30 13:17 UTC
Labels: bug, duplicate
