### ISSUE TITLE
[BUG] flashcard tags - 5 tag limit

### ISSUE THREAD

**Issue by johnsonsuqs** [st3v3nmw/obsidian-spaced-repetition#427] opened 2022-03-25 11:01 UTC
act on "Specify flashcard tags in settings" 

I set six tags as decks but only have five decks shown in flashcards view , I am sure they have been separated by space or newlines.

I mean:
in config:
  flashcard tags    is set as " #tag1 #tag2 #tag3 #tag4 #tag5 #tag6"
in review flashcards
but only  tag1  tag2   #tag4 #tag5  be shown as decks, tag6 is lost. whatever I could do  it doesn't show

 all tags is english    even I directly write tag6 in data.json it still doesn't play, I think the limit of decks is five

the plugin is very good, it is very useful to me ,thanks.

**Comment by fibushj** [comment] 2022-05-20 11:58
Hi @st3v3nmw, the same bug occurs to me too. Can you please fix this 5-tags limit?

**Comment by ronzulu** [comment] 2024-01-11 13:30
Hi @johnsonsuqs this doesn't appear to be still an issue. Are you able to verify and close this issue?

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/bff3d680-d0e9-472b-b79b-0f16cae5a4d5)


Cheers
Ronny

**Comment by ronzulu** [comment] 2024-01-30 11:14
Hi @johnsonsuqs 

We haven't heard back from you, and I can't reproduce the issue.

I'll close this now, but feel free to reopen if this is still an issue.

Cheers
Ronny

**Closed by ronzulu** 2024-01-30 11:14 UTC
Labels: bug
