### ISSUE TITLE
[BUG] LaTeX math changed upon note review

### ISSUE THREAD

**Issue by deliriouserror94** [st3v3nmw/obsidian-spaced-repetition#527] opened 2022-11-09 17:56 UTC
**Describe the bug**
If using LaTeX math with `$$` above a horizontal divider (`---`), the `$$` is replaced with `$` upon note review, i.e. `$$ \int_{0}^{100}x^{2} $$` becomes `$ \int_{0}^{100}x^{2} $`

This appears to be caused by two bugs:
1.  `SCHEDULING_INFO_REGEX` matching until the last `---` in the file. 
    - Changing it from `/^---\n((?:.*\n)*)sr-due: (.+)\nsr-interval: (\d+)\nsr-ease: (\d+)\n((?:.*\n)*)---/;` to `/^---\n((?:.*\n)*)sr-due: (.+)\nsr-interval: (\d+)\nsr-ease: (\d+)\n((?:.*\n)?)---/;` matches only until the next `---` and does not cause this issue
2. All occurrences of `$$` in the front matter are replaced with `$`

**To Reproduce**
1. Write a note using LaTeX math with `$$` to open and close the block
2. Add a horizontal divider (`---`) below the math block
3. Add the `#review` tag to the note
4. Review note as easy, good, or hard
5. All occurrences of `$$` before the last `---` will have been replaced with `$`

**Expected behavior**
No text outside of the scheduling info/flashcard info will be changed by the plugin.

**Versions:**
-   OS: Linux (Debian 10)
-   Obsidian version: v.1.0.3, installed through flatpak
-   Plugin version: v1.8.0
-   IInstaller version: '5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.0.3 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36'

**Additional context**
Reviewing this note will cause the issue for the first math block, but not the second:

```markdown
---
sr-due: 2022-11-10
sr-interval: 1
sr-ease: 140
---

This is some text.

---

This math will be changed

$$ \int_{0}^{100}x^{2} $$

---

This math will be fine

$$ \int_{0}^{100}x^{2} $$


#review 
```

**Comment by AB1908** [comment] 2022-11-21 17:38
Since you've found the root cause, do you want to attempt fixing it? I am happy to provide some feedback/guidance if you need it.

**Comment by st3v3nmw** [comment] 2022-12-30 08:02
Fix was merged, should be available in the next release

**Closed by st3v3nmw** 2022-12-30 08:02 UTC
Labels: bug
