### ISSUE TITLE
Can add "Convert **italic text** to clozes?"?

### ISSUE THREAD

**Issue by sparklau** [st3v3nmw/obsidian-spaced-repetition#423] opened 2022-03-18 13:35 UTC
Can add "Convert **italic text** to clozes?"?

Highlight and bold text were in use for the other purposes.

Thanks for your excellent work!

**Comment by MotaOcimar** [comment] 2022-03-24 11:25
Related with #387

**Comment by st3v3nmw** [comment] 2022-10-12 19:33
Duplicate of #387 
Will be tracking this feature request there

**Closed by st3v3nmw** 2022-10-12 19:33 UTC
Labels: enhancement
