### ISSUE TITLE
[BUG] Notes in 'New' are not included in review queue

### ISSUE THREAD

**Issue by dsteinbock** [st3v3nmw/obsidian-spaced-repetition#274] opened 2021-08-24 23:58 UTC
**Describe the bug**

As part of incremental writing, I'm constantly adding new notes to my review queue. The problem is, when I execute the 'Open a note for review' command, the plugin never shows notes in 'New'. It only shows notes that have already been reviewed. This is unexpected behavior and means that new notes are not easily scheduled into the review queue. I have to manually click on each note, one by one, under 'New' and execute a review command (good/easy/hard) to get them scheduled. 

This breaks the easy workflow of running 'Open a note for review' via hotkey.

**To Reproduce**

1. Tag a new note with the review tag, e.g. #review
2. Run 'Open a note for review' command repeatedly
3. The new note never comes up for review

**Expected behavior**

'New' notes should be treated as a fallback for 'Today'. When you run 'Open a note for review' command, review notes in Today first. When Today is empty, review notes in New. When New is empty, review notes scheduled for the future.

This would restore the easy workflow of running 'Open a note for review' via hotkey, knowing all notes will be reviewed properly.

**Versions (please complete the following information):**
 - OS: MacOS
 - Obsidian version: v0.12.14
 - Plugin version: v1.6.1
 - "5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/0.10.6 Chrome/87.0.4280.88 Electron/11.1.0 Safari/537.36"

**Comment by RitchieFlick** [comment] 2021-08-25 06:53
I can confirm this behaviour on **Windows** as well: Obsidian version: v0.12.12

**Comment by st3v3nmw** [comment] 2021-08-28 12:32
The fix for this should be available in the next release.

**Comment by RitchieFlick** [comment] 2021-08-30 05:35
> I can confirm this behaviour on **Windows** as well: Obsidian version: v0.12.12

The recent update has fixed the problem on my installation 👍

**Comment by 11-check-it-out** [comment] 2021-08-30 10:47
It seems that the number in state bar is still wrong? It doesn't count those notes in New.
![image](https://user-images.githubusercontent.com/47976614/131328104-052039a4-8713-4e82-adca-a1428d786798.png)

**Comment by MattSPalmer** [comment] 2021-08-30 13:33
I don't think that's a regression, it wasn't counting new notes even before support for multiple note queues was added.

**Comment by st3v3nmw** [comment] 2021-08-30 14:56
@11-check-it-out, @MattSPalmer's right. That only counts notes that have already been scheduled and are due for reviewing.

**Comment by st3v3nmw** [comment] 2021-08-30 14:56
Closing since this was fixed.

**Closed by st3v3nmw** 2021-08-30 14:56 UTC
Labels: bug
