### ISSUE TITLE
The font-size is much to small for studying and not adjustable[BUG]

### ISSUE THREAD

**Issue by Superfeuchter** [st3v3nmw/obsidian-spaced-repetition#497] opened 2022-09-09 11:27 UTC
The font-size of cards and overview is much to small and not adjustable.

I tried some adjustments in style settings of my theme (minimal), but no chance.
I tested the plugin in standard-theme, but with the same effect.

The font-size should be the same size as the notes are.

![image](https://user-images.githubusercontent.com/83219956/189338241-8bfcdcc6-16dc-4859-a9f2-7ee2e3f1b502.png)
![image](https://user-images.githubusercontent.com/83219956/189339607-6c90371b-721e-4681-932e-64806f18d241.png)

Obsidian-Version: v0.16.2 on Windows 10
The plugin-version is: v1.8.0

Can you please make the fonts adjustable or at least bigger?

**Comment by davenukem** [comment] 2022-09-18 17:13
Going to chime in here! The ability to increase the size of text in the review window would be MUCH appreciated and helpful!

Incredible work on this addon - will be sure to donate as soon as next paycheck comes in!

**Comment by martincodez** [comment] 2022-10-05 11:38
Yeah this is probably not a bug — but would be extremely nice to adjust the font here

**Comment by st3v3nmw** [comment] 2022-10-12 18:15
This should be fixed in #480, will update after the change goes out

**Comment by sheilagomes** [comment] 2022-11-15 12:57
I was able to fix it by tweaking the `styles.css` file that can be found in `.obsidian/plugins/obsidian-spaced-repetition` (it's a hidden folder inside the vault's folder). I added `font-size: 1.5em;` to the id `#sr-flashcard-view`and to the class `.sr-response`

**Comment by Superfeuchter** [comment] 2022-11-15 16:50
Thank you sheilahomes,
I tried this out, but unfortunately with no effect. But it's a very good idea. Thanks!

**Comment by st3v3nmw** [comment] 2022-12-18 06:48
> This should be fixed in #480, will update after the change goes out

The flashcard size should now match the editor's, does that help?

**Comment by Superfeuchter** [comment] 2022-12-18 20:14
Thank you very much!
It looks much better, so I can work with.

**Closed** 2022-12-22 05:37 UTC
Labels: bug, awaiting release
