### ISSUE TITLE
This plugin is very good,But this often happens when I review my notes

### ISSUE THREAD

**Issue by johnsonsuqs** [st3v3nmw/obsidian-spaced-repetition#445] opened 2022-05-10 11:47 UTC
![image](https://user-images.githubusercontent.com/100344601/167621246-8ec9ec43-5034-437d-a4bb-f03e0de9c030.png)
This plugin is very good,But this often happens when I review my notes。
I found out bugs in the code snippet marked in red,Because if you ctrl+z and do it again,the SCHEDULING_INFO_REGEX.test(fileText)=trun, the plugin do the note  according to the first condition , I think it may be the problem with obsidian itself     so I  Commenting out this code snippet  at least it doesn’t go wrong again,   But I don't know if this will have unintended consequences, I think you maybe has a better idea. 
![image](https://user-images.githubusercontent.com/100344601/167621411-f9481351-9927-4c6d-9ab8-bbdd2036738b.png)

**Comment by st3v3nmw** [comment] 2022-10-12 19:06
Duplicate of #504 
We'll be tracking the fix there

**Closed as completed by st3v3nmw** 2022-10-12 19:06 UTC
Labels: bug
