### ISSUE TITLE
[FEAT] Decks that share flashcards

### ISSUE THREAD

**Issue by MePando** [st3v3nmw/obsidian-spaced-repetition#444] opened 2022-05-08 16:44 UTC
I don't know if this could be a thing or not, or even if other people would find this is useful, but I was wondering if you can add the possibility of having decks which share flashcards:

Example:
In your space repetition plugin option menu set as flashcard tags both tag1 tag2.
Then you create a noteA with both tag1 and tag2 and define some flashcards in it.
Now all the flashcards in the noteA should appear in both decks.

I think that decks could share the same  so if you review q (a flashcard that deck_tag1 has in common with deck_tag2) in deck_tag1 there is no need to review q again in deck_tag2.

I don't know if I'm the only one, but I think this could be so useful.

Hope I was clear enough.
Thanks

**Comment by vasalx** [comment] 2022-06-21 13:03
@MePando Just add #flashcard (or whatever) as your flashcards note tag (in the settings) and use #flashcard/tag1 and #flashcard/tag2 in the notes. You will get two sub-decks 'tag1' and 'tag2' under the 'flashcard' deck. The sub-decks can also share cards: if a note contains both nested tags (e.g., #flashcard/tag1 #flashcard/tag2 ), cards from it will be present in both sub-decks. At least it is how it seems to work for me.

**Comment by putzwasser** [comment] 2022-09-08 12:17
I guess the "problem" here is related to #495

**Comment by vasalx** [comment] 2022-09-08 14:00
@putzwasser I have retested it just now and can confirm that the behavior is the same as in your case on Windows. 
It may be just my lousy attention, but I was sure I have the same card under tag1 and tag2 at the time of initial posting.

**Comment by st3v3nmw** [comment] 2022-10-12 19:10
Duplicate of #495
Will be tracking this issue there

**Closed by st3v3nmw** 2022-10-12 19:10 UTC
Labels: enhancement
