### ISSUE TITLE
[BUG] Decks not visible when reviewing flashcards

### ISSUE THREAD

**Issue by semits20** [st3v3nmw/obsidian-spaced-repetition#87] opened 2021-05-18 05:02 UTC

**Comment by semits20** [comment] 2021-05-18 05:05
Obsidian Version: 0.12.3
OS: Windows 10

at the time of reviewing flashcards using the sidebar icon, flashcards are being shown but not the decks.

**Comment by st3v3nmw** [comment] 2021-05-18 05:09
What about the plugin version?
Are there any error logs on the developer console? i.e. `ctrl` + `shift` + `i`

**Comment by semits20** [comment] 2021-05-18 05:13
Plug In Version: 1.4.6

I am not a technical person but as you have suggested the hotkey i have checked it, i couldn't see any error in developer console.

**Comment by jakeoung** [comment] 2021-05-18 16:59
A related issue: when I open the reviewing by shortcut, it will not show any cards I have.

**Comment by st3v3nmw** [comment] 2021-05-20 15:09
@semits20, I can't reproduce this issue. I'm not sure what the problem might be.

@jakeoung, I fixed that issue. I'll make the release available soon.

**Comment by st3v3nmw** [comment] 2021-05-31 07:43
Since you managed to list decks, I'll close this issue.

**Closed by st3v3nmw** 2021-05-31 07:43 UTC
Labels: bug
