### ISSUE TITLE
[Bug]: Stopped working on iPhone and iPad after 1.12.5

### ISSUE THREAD

**Issue by Ti-mmm** [st3v3nmw/obsidian-spaced-repetition#1037] opened 2024-08-04 17:16 UTC
### Describe the bug

I am unable to use the plugin after updating to the newest version on my iPhone and iPad. The plugin works fine on PC. Even with all other plugins disabled and the default theme, it still doesn‘t work.

### To Reproduce

1. Be on iOS/iPadOS 16.7 (not sure if needed)
2. Update the plugin to newest version
3. try to open "Review Flashcards"
4. menu does not open

### Expected behavior

After doing command „Spaced Repetition: Review flashcards from all Notes“ the menu should open, which it does not.

### OS of your device

iOS 17.6 / iPadOS 17.6

### Obsidian version

1.6.7

### Plugin version

1.12.5

**Comment by ronzulu** [comment] 2024-08-05 12:59
Curious, were you using the same vault on the PC as on the iPhone/iPad?

**Comment by iliankai** [comment] 2024-08-05 13:38
You are not alone. I'm having the same issue with iOS 17.6 / iPadOS 17.6.
I tried to uninstall and then to install the plugin. Didn't work.

**Comment by ronzulu** [comment] 2024-08-06 11:41
Thanks for the info. Interesting that the same vault works on the PC, and a fresh vault works on the mobile. This seems to imply that there is something within the vault that triggers specific code that isn't working in the mobile environment.

If you could please try out the beta 12 release, as per https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/1033#issuecomment-2271083766

Cheers
Ronny

**Comment by Ti-mmm** [comment] 2024-08-06 12:27
Hello again. I seem to have found a solution. The issue seems to be the data.json, and the setting causing the crash is "noteFoldersToIgnore", which I had set to `"noteFoldersToIgnore": [ "Personal" ],`. Changing it to `"noteFoldersToIgnore": [],` which should be the default setting fixed the issue and let me use the plugin again on my phone.
Also, not sure if this is still needed info but I did try changing to the beta 12 release as well as 1.12.4 and that did not solve the issue.

**Comment by Ti-mmm** [comment] 2024-08-06 12:43
Here's the log error too:
`Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'this.baseDeckTree.getDeck')`

**Comment by ronzulu** [comment] 2024-08-07 01:17
Thanks for that, and that is largely consistent with #1033. 

The reason why your workaround worked is that if `noteFoldersToIgnore` is empty, then there is no attempt to call the (missing on mobile) system API `normalize`.

**Comment by iliankai** [comment] 2024-08-07 11:48
![IMG_1774](https://github.com/user-attachments/assets/05622da7-06b1-4d8e-bf40-8b16c6ca7837)
Thanks for the workaround, @Ti-mmm .
I removed all the words in "Folders to ignore ", then "Review Flashcards" could bring out the menu.

**Comment by TfTHacker** [comment] 2024-08-30 04:52
I have been using this plugin daily for a few years, and I can confirm it stopped working some time back. Today I removed the exclusion folders and it started to work again.

I am on iPhone.  I am just happy it is working again, the folder exclusion is not such a big deal, but of course it would be nice to have it working.

**Comment by ronzulu** [comment] 2024-09-02 11:27
Hi this has been fixed in https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/1048, but not yet released.

**Closed** 2024-09-02 12:39 UTC
Labels: bug
